resource_files/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('accounts.urls')),
    path('accounts', include('django.contrib.auth.urls')),
    path('', include('store.urls')),

]

store/urls.py
from django.urls import path, include
from django.contrib import admin
# from django.conf import settings
# from django.conf.urls.static import static
from . import views


from django.contrib.auth.views import LoginView
from .forms import CustomAuthenticationForm

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT) 
#     # urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


urlpatterns = [
    path('',views.store, name="store"),
    path('cart/',views.cart, name="cart"),
    path('checkout/',views.checkout, name="checkout"),
    path('category/<int:id>/',views.category, name="category"),
    path('update_item/', views.updateItem, name="update_item"),
    path('process_url_from_client/', views.process_url_from_client, name="process_url_from_client"),
    path('process_order/', views.processOrder, name="process_order"),
    path('products/<int:id>/', views.product_detail, name='product'),
    path('product/addcomment/<int:proid>', views.addcomment, name='addcomment'),
    path('about/', views.about, name='about'),
    path('autocomplete/', views.autocomplete, name='autocomplete'),
    path('signup/', views.sign_up, name='signup'),
    path('admin/', admin.site.urls),
    path('search/',views.search, name='search'),
    path('profile/', views.profile, name='profile'),
    path('order-summary/',views.order_details, name='order_summary'),
    path('payment_succesful/',views.paymentSuccess, name='paymentSuccessful'),
    path('contact/',views.contact, name='contact'),
    path('success/', views.successView, name='success'),
    path(
        'login/',
        LoginView.as_view(
            template_name="registration/login.html",
            authentication_form=CustomAuthenticationForm
            ),
        name='login'
    ),

    # path('profile/edit/', views.edit_profile, name='edit_profile')
    # path('', views.home_view, name="home"),
    # path('category_detail/<int:id>/<slug:slug>', views.category_detail, name='category')
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.shortcuts import reverse
from django.db.models.signals import pre_save
from django.template.defaultfilters import slugify
from django.db.models import Avg
from PIL import Image
from django.utils import timezone

CATEGORY_CHOICES = (
    ('A', 'Ambulatory'),
    ('G', 'Gloves'),
    ('O', 'Orthopedic'),
    ('R','Respiratory'),
    ('SK', 'Skin Care'),
    ('SY', 'Syringes / Needles / Infusion')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)
SHIPPING_METHODS = [('option1','Standard'),('option2','Express'),('option3','Rush')]


class Category(models.Model):
    name = models.CharField(max_length=20,default=" ")

    @staticmethod
    def get_all_categories():
        return Category.objects.all()

    @staticmethod
    def get_select(id):
        return Category.objects.get(id=id)


    def __str__(self):
        return self.name




# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg' , upload_to='profile_pics')
    def __str__(self):
        return f'{self.user.username} Profile'

    # def save(self):
    #     super().save()
    #     img = Image.open(self.image.path)

    #     if img.height >300 or img.width >300:
    #         output_size = (300,300)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)

class Product(models.Model):

    name = models.CharField(max_length=200, null=True)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True, blank=False)
    # category = models.CharField(choices =CATEGORY_CHOICES, max_length=2, null = True, blank = True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE, default=1)
    image = models.ImageField(null=True, blank=True, upload_to='images/')
    secondImage = models.ImageField(null=True, blank=True, upload_to='images/')
    # user field needs to allow nulls
    description = models.TextField(null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)




    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url= self.image.url
        except:
            url = ''
        return url

    @property
    def imageURL_2(self):
        try:
            url = self.secondImage.url
        except:
            url = ''
        return url



    @staticmethod
    def get_products_by_id(ids):
        return Product.objects.filter(id__in=ids)

    @staticmethod
    def get_all_products():
        return Product.objects.all()

    @staticmethod
    def get_all_products_by_categoryid(category_id):
        if category_id:
            return Product.objects.filter(category = category_id)
        else:
            return Product.get_all_products()
    @property
    def avg_rating(self):
        sum = 0
        comments = Comment.objects.filter(product_id=self.id)
        for comment in comments:
            sum += comment.rate
        if len(comments) >0:
            return int(sum/len(comments))
        else:
            return 0

    @property
    def avg_len(self):
        comments = Comment.objects.filter(product_id=self.id)
        if len(comments)>0:
            return len(comments)
        else:
            return 0

    @property
    def testLength(self):
        comments = Comment.objects.filter(product_id=self.id)
        if len(comments) > 0:
            return len(comments)
        else:
            return 0




def slug_generator(sender,instance, *args, **kwargs):
        if not instance.slug:
            instance.slug='SLUG'


pre_save.connect(slug_generator, sender=Product)

class Order(models.Model):
    # ref_code = models.CharField(max_length=15, blank=True,null=True)
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null = True)
    shipping_methods = models.BooleanField(default=False)
    ship_window = models.BooleanField(default=False)
    service = models.CharField(
                    max_length = 20,
                    choices = SHIPPING_METHODS, # Just a list of Ground, 2day, etc
                    default = "Standard")

    def __str__(self):
        if self.id==None:
            return "ERROR-ORDER IS NULL"
        return str(self.id)
  
    def get_order_items(self):
        return OrderItem.objects.filter(order=self)

    # def __str__(self):
    #     return '{0} - {1}'.format(self.owner, self.ref_code)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total
    
    # def save(self, force_insert=False, force_update=False, using=None):
    #     self.save(force_insert, force_update, using)


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    date_ordered= models.DateTimeField(null=True)
    
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address


class Comment(models.Model):
    STATUS =(
        ('New', 'New'),
        ('True','True'),
        ('False', 'False'),
    )

    RATING = (
        (1,1),
        (2,2),
        (3,3),
        (4,4),
        (5,5),
    )


    product= models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    subject = models.CharField(max_length=998, blank=True)
    comment = models.CharField(max_length=8000, blank=True)
    rate = models.IntegerField(default=1)
    ip = models.CharField(max_length=20, blank=True)
    status=models.CharField(max_length=10, choices=STATUS, default='New')
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)



    def __str__(self):
        return self.subject

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment', 'rate']



        # widget = {
        #     'subject': TextInput(attrs={'class':'input', 'placeholder': 'subject'}),
        #     'message' : Textarea(attrs={'class':'input', 'placeholder':'Your Review'}),
        #     'rating': Textarea(attrs={'class': 'input'}),
        #     }

class Coupon(models.Model):
    code = models.CharField(max_length=50, unique=True)
    valid_from = models.DateTimeField(default=timezone.now)
    valid_to = models.DateTimeField()
    discount = models.DecimalField(max_digits=5, decimal_places=2)
    active = models.BooleanField(default=True)

    def is_valid(self):
        now = timezone.now()
        return self.active and self.valid_from <= now <= self.valid_to

    def apply_discount(self, total):
        if self.is_valid():
            return total - (total * (self.discount / 100))
        return total

    def __str__(self):
        return self.code

store/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm, UsernameField

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Order
from django.forms.widgets import TextInput, PasswordInput

class CustomAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(CustomAuthenticationForm, self).__init__(*args, **kwargs)

    username = UsernameField(widget=TextInput(attrs={
        'class': 'ms-input w-input',
        'autofocus': True,
        'placeholder': 'Username or Email'
    }))
    
    password = forms.CharField(widget=PasswordInput(attrs={
        'class': 'ms-input w-input',
        'placeholder': 'Password'
    }))


class RegisterForm(UserCreationForm):
    # email= forms.EmailField()
    username = forms.CharField(max_length=30, widget=TextInput(attrs={
        'class': 'ms-input w-input',
        'autofocus': True,
        'placeholder': 'Username or Email'
    }))

    password1 = forms.CharField(
        label='Enter Password',
        widget=PasswordInput(attrs={
        'class': 'ms-input w-input',
        'placeholder': 'Enter Password'
    }))

    password2 = forms.CharField(
        label='Confirm Password',
        widget=PasswordInput(attrs={
        'class': 'ms-input w-input',
        'placeholder': 'Confirm Password'
    }))
    
    email = forms.EmailField(max_length=200, widget=TextInput(attrs={
        'class': 'ms-input w-input',
        'placeholder': 'Email'
    }))
    class Meta:
        model = User
        fields = ["username", "email","password1","password2"]
     

   
    

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(max_length=200, widget=TextInput(attrs={
        'class': 'ms-input w-input',
        'placeholder': 'Email'
    }))    
    username = UsernameField(widget=TextInput(attrs={
        'class': 'ms-input w-input',
        'autofocus': True,
        'placeholder': 'Username or Email'
    }))
    class Meta:
        model= User
        fields = ['username', 'email']





class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']


class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)



class ShippingForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['shipping_method']
    SHIPPING_METHODS = [('option1','Standard'),('option2','Express'),('option3','Rush')]
    shipping_method = forms.TypedChoiceField(label='',choices=SHIPPING_METHODS,widget=forms.RadioSelect)

state_names = ["Alaska", "Alabama", "Arkansas", "American Samoa", "Arizona", "California", "Colorado", "Connecticut", "District ", "of Columbia", "Delaware", "Florida", "Georgia", "Guam", "Hawaii", "Iowa", "Idaho", "Illinois", "Indiana", "Kansas", "Kentucky", "Louisiana", "Massachusetts", "Maryland", "Maine", "Michigan", "Minnesota", "Missouri", "Mississippi", "Montana", "North Carolina", "North Dakota", "Nebraska", "New Hampshire", "New Jersey", "New Mexico", "Nevada", "New York", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Puerto Rico", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Virginia", "Virgin Islands", "Vermont", "Washington", "Wisconsin", "West Virginia", "Wyoming"]
states = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA", 
          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", 
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", 
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", 
          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]

class StateForm(forms.Form):
    state_names = [('Alaska', 'AK'), ('Alabama', 'AL'), ('Arkansas', 'AR'), ('Arizona', 'AZ'), ('California', 'CA'), ('Colorado', 'CO'), ('Connecticut', 'CT'), ('District of Columbia', 'DC'), ('Delaware', 'DE'), ('Florida', 'FL'), ('Georgia', 'GA'), ('Hawaii', 'HI'), ('Iowa', 'ID'), ('Idaho', 'IL'), ('Illinois', 'IN'), ('Indiana', 'IA'), ('Kansas', 'KS'), ('Kentucky', 'KY'), ('Louisiana', 'LA'), ('Massachusetts', 'ME'), ('Maryland', 'MD'), ('Maine', 'MA'), ('Michigan', 'MI'), ('Minnesota', 'MN'), ('Missouri', 'MS'), ('Mississippi', 'MO'), ('Montana', 'MT'), ('North Carolina', 'NE'), ('North Dakota', 'NV'), ('Nebraska', 'NH'), ('New Hampshire', 'NJ'), ('New Jersey', 'NM'), ('New Mexico', 'NY'), ('Nevada', 'NC'), ('New York', 'ND'), ('Ohio', 'OH'), ('Oklahoma', 'OK'), ('Oregon', 'OR'), ('Pennsylvania', 'PA'), ('Rhode Island', 'RI'), ('South Carolina', 'SC'), ('South Dakota', 'SD'), ('Tennessee', 'TN'), ('Texas', 'TX'), ('Utah', 'UT'), ('Virginia', 'VT'), ('Vermont', 'VA'), ('Washington', 'WA'), ('Wisconsin', 'WV'), ('West Virginia', 'WI'), ('Wyoming', 'WY')]
    state = forms.ChoiceField(label='', choices = state_names, widget = forms.Select(attrs={ 'class':'form-control','name':'state'}))


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'input-text',
        'placeholder': 'Enter coupon code'
    }),
    label=False  # Set label to False to remove the label
)    

store/templates/store/categories.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a style="border: none; text-transform:capitalize;margin-left:10px; color:#90D7A5;" href="/">Home</a></li>
                    <li class="breadcrumb-item" style="border: none; text-transform:capitalize;">{{category_select}}</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="container" id="store">
    <div class="row">
        {% for product in page.object_list %}
        <div class="col-md-3 col-sm-6">
            <div class="product-grid">
                <div class="product-image">
                    <a href="#">
                        <img class="pic-1" src="{{product.imageURL}}">
                        <img class="pic-2" src="{{product.imageURL_2}}">

                    </a>
                    <ul class="social">
                        <li><a href="{% url 'product' product.id %}" data-tip="Quick view"><i class="fa fa-search"></i></a>
                        </li>
                        <!--                        <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>-->
                        <li><a href="" data-product={{product.id}} data-action="add" class="add-btn update-cart"
                               data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                    </ul>
                    <a href="#" data-product={{product.id}} data-action="add"
                       class="select-options add-btn update-cart">Add to Cart
                    </a>

                </div>
                <div class="product-content row">
                    <div class="col"><h3 class="title"><a href="#">{{product.name}}</a></h3>
                        <div class="price">${{product.price|floatformat:2}}</div>
                    </div>
                    <div class="col text-center">

                        <ul class="rating">
                            <i class="fa fa-star{% if product.avg_rating < 1 %}-o empty{% endif %}"></i>
                            <i class="fa fa-star{% if product.avg_rating < 2 %}-o empty{% endif %}"></i>
                            <i class="fa fa-star{% if product.avg_rating < 3 %}-o empty{% endif %}"></i>
                            <i class="fa fa-star{% if product.avg_rating < 4 %}-o empty{% endif %}"></i>
                            <i class="fa fa-star{% if product.avg_rating < 5 %}-o empty{% endif %}"></i>
                            <span style="color:#1e3799"><strong>({{product.testLength}})</strong></span>

                        </ul>

                    </div>

                </div>

            </div>
        </div>
        {% endfor %}


    </div>
    <nav>
        <ul class="pagination justify-content-center">
            {% if page.has_previous %}
            <a class="pagination-action" href="?page=1"><i class="fa fa-angle-double-left" aria-hidden="true"></i></a>
            <a class="pagination-action" href="?page={{ page.previous_page_number }}"><i class="fa fa-angle-left"
                                                                                         aria-hidden="true"></i></a>
            {% endif %}
            {% for pg in page.paginator.page_range %}
            {% if page.number == pg %}
            <span class="pagination-current">{{pg}}</span>
            {% elif pg > page.number|add:'-3' and pg < page.number|add:'3' %}
            <a class="pagination-number" href="?page={{pg}}">{{pg}}</a>
            {% endif %}
            {% endfor %}
            {% if page.has_next %}
            <a class="pagination-action" href="?page={{page.next_page_number}}"><i class="fa fa-angle-right"
                                                                                   aria-hidden="true"></i></a>
            <a class="pagination-action" href="?page={{page.paginator.num_pages}}"><i class="fa fa-angle-double-right"
                                                                                      aria-hidden="true"></i></a>
            {% endif %}
        </ul>
    </nav>
</div>




{% endblock content %}

store/templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<div class="checkout-container">
	<div class="left-checkout">
		<div class="main-cart-section main-cart-section_0 cart-background enhanced-section">
			<div class="cart-row cart_gap2 cart-row_1-4_1-2_1-4">
				<div
				class="cart-section cart-column cart-column_1_4 cart-column_0 mix-blend-passthrough cart-column_single">
				<div
					class="enhanced_module snippet snippet_0 clickable-component  text-align-left  snippet_position_left bg-layout_light">
					<div class="snippet_content">
						<div class="main-snippet-img"><span class="image-wrap"><span
									class="scroll-trigger animation_off animation_off_tablet animation_off_phone styled-icon animated"><i
										class="fa fa-shopping-bag" aria-hidden="true"></i>
								</span></span>
						</div>
						<div class="snippet_container">
							<h4 class="enhanced_module_header"><span>Shop</span></h4>
						</div>
					</div>
				</div>
				<div
					class="enhanced_module snippet snippet_0 clickable-component  text-align-left  snippet_position_left bg-layout_light">
					<div class="snippet_content">
						<div class="main-snippet-img"><span class="image-wrap"><span
									class="scroll-trigger animation_off animation_off_tablet animation_off_phone styled-icon animated"><i
										class="fa fa-shopping-cart" ></i></span></span>
						</div>
						<div class="snippet_container">
							<h4 class="enhanced_module_header"><span>Cart</span></h4>
						</div>
					</div>
				</div>
				<div
					class="enhanced_module snippet snippet_1 clickable-component  text-align-left  snippet_position_left bg-layout_light">
					<div class="snippet_content">
						<div class="main-snippet-img"><span class="image-wrap"><span
									class="scroll-trigger animation_off animation_off_tablet animation_off_phone styled-icon animated"><i
										class="fa fa-credit-card" aria-hidden="true"></i></span></span>
						</div>
						<div class="snippet_container">
							<h4 class="enhanced_module_header"><span>Checkout</span></h4>
						</div>
					</div>
				</div>
			</div>
			</div>
		</div>
	</div>
	<div class="center-shipping">
		<div class="box-element" id="form-wrapper">
			<!-- <form method="POST">
					{% csrf_token %}
					{{ form }}
					<button type="submit" value="submit">Submit</button>
				</form> -->
		
				<form id="form" method="POST">
					<div id="user-info">
						<div class="form-field">

							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">

							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>

					<div id="shipping-info">
						<h4>Shipping Information:</h4>
						<hr>
						<div class="form-field">

							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>

						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Country..">
						</div>
						<div class="form-field">

							<!-- <input class="form-control" type="text" name="state" placeholder="State.."> -->
							<!-- <select class="form-control" name="state" onchange="this.form.submit()" id="id_state" >
								<option selected="selected">State...</option>
								{% for stat in states %}	
								<option>{{stat}}</option>
								{% endfor %}
							</select> -->
							{% csrf_token %}
							{{ form }}
						</div>
					</div>

					<!-- <button type="submit" value="submit">Submit</button> -->
					<hr>
					<input id="form-button" class="button btn-block w-button" type="submit" value="Continue">

				</form>
			
		</div>

		<br>
		<div class="box-element hidden" id="payment-info">
			<h4>Paypal Options</h4>
			<!--<button id="make-payment">Make payment</button>-->
			<div id="paypal-button-container"></div>
		</div>
	</div>
	<div class="cart-information">
		<h4 class="d-flex justify-content-between align-items-center mb-3">
			<span class="text-muted">Your cart</span>
			<span class="badge badge-secondary badge-pill">{{order.get_cart_items}}</span>
		</h4>
		<ul class="list-group mb-3">
			{% for item in items %}
			<li class="list-group-item d-flex justify-content-between lh-condensed">
				<div>
					<!--                     <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>-->
					<h6 class="my-0">
						<p>{{item.product.name}}</p>
					</h6>
					<small class="text-muted">
						<p>Quantity: {{item.quantity}}</p>
					</small>
				</div>
				<span class="text-muted">
					<p>${{item.product.price}}</p>
				</span>

			</li>

			{% endfor %}
			<li class="list-group-item d-flex justify-content-between">
				<small class="text-muted">
					<p>Tax</p>
				</small>
				<strong>${{order.get_cart_total|floatformat:2}}</strong>
			</li>
			<li class="list-group-item d-flex justify-content-between">
				<small class="text-muted">
					<p>Shipping</p>
				</small>
				<strong>${{order.get_cart_total|floatformat:2}}</strong>
			</li>
			<li class="list-group-item d-flex justify-content-between">
				<span>Total (USD)</span>
				<strong>${{order.get_cart_total|floatformat:2}}</strong>
			</li>
		</ul>
	</div>
</div>









<script
src="https://www.paypal.com/sdk/js?client-id=AaVb6b-TD7kOwTY3eN5mE-q4508Hf86CZTjIRF01DwNm8I70dOP2eNK65b1XWgbsiRjESpJE6KmKwhTn&currency=USD&disable-funding=credit"></script>

<script>
	var total = '{{order.get_cart_total}}'
	// Render the PayPal button into #paypal-button-container
	paypal.Buttons({

		style: {
			color: 'blue',
			shape: 'rect',
		},

		// Set up the transaction
		createOrder: function (data, actions) {
			return actions.order.create({
				purchase_units: [{
					amount: {
						value: parseFloat(total).toFixed(2)
					}
				}]
			});
		},

		// Finalize the transaction
		onApprove: function (data, actions) {
			return actions.order.capture().then(function (details) {
				// Show a success message to the buyer
				submitFormData()
			});
		}

	}).render('#paypal-button-container');
</script>

<script type="text/javascript">
	var shipping = '{{order.shipping}}'

	if (shipping == 'False') {
		document.getElementById('shipping-info').innerHTML = ''
	}

	if (user != 'AnonymousUser') {
		document.getElementById('user-info').innerHTML = ''
	}

	if (shipping == 'False' && user != 'AnonymousUser') {
		//Hide entire form if user is logged in and shipping is false
		document.getElementById('form-wrapper').classList.add("hidden");
		//Show payment if logged in user wants to buy an item that does not require shipping
		document.getElementById('payment-info').classList.remove("hidden");
	}

	var form = document.getElementById('form')
	form.addEventListener('submit', function (e) {
		e.preventDefault()
		console.log('Form Submitted...')
		document.getElementById('form-button').classList.add("hidden");
		document.getElementById('payment-info').classList.remove("hidden");
	})

	/*
	document.getElementById('make-payment').addEventListener('click', function(e){
		submitFormData()
	})
	*/

	function submitFormData() {
		console.log('Payment button clicked')

		var userFormData = {
			'name': null,
			'email': null,
			'total': total,
		}

		var shippingInfo = {
			'address': null,
			'city': null,
			'state': null,
			'zipcode': null,
		}

		if (shipping != 'False') {
			shippingInfo.address = form.address.value
			shippingInfo.city = form.city.value
			shippingInfo.state = form.state.value
			shippingInfo.zipcode = form.zipcode.value
		}


		if (user == 'AnonymousUser') {
			userFormData.name = form.name.value
			userFormData.email = form.email.value
		}

		console.log('Shipping Info:', shippingInfo)
		console.log('User Info:', userFormData)

		var url = "/process_order/"
		fetch(url, {
			method: 'POST',
			headers: {
				'Content-Type': 'applicaiton/json',
				'X-CSRFToken': csrftoken,
			},
			body: JSON.stringify({ 'form': userFormData, 'shipping': shippingInfo }),

		})
			.then((response) => response.json())
			.then((data) => {
				console.log('Success:', data);
				alert('Transaction completed');

				cart = {}
				document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"

				window.location.href = "{% url 'paymentSuccessful' %}"

			})
	}
</script>


{% endblock content %}